/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.qlbh.view;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class DangKyJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangKyJDialog
     */
    public DangKyJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
private void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
        JOptionPane.showMessageDialog(null, noiDungThongBao,
                tieuDeThongBao, icon);
    }
 private boolean KiemTraChuaChuVaSo(String chuoi) {
        boolean ketqua = false;
        Pattern p = Pattern.compile("[a-zA-Z][0-9]");
        Matcher m = p.matcher(chuoi);
        if (!(chuoi == chuoi.toLowerCase())) {
            ketqua = m.find();
        }
        return ketqua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtRetypePasswword = new javax.swing.JPasswordField();
        Themtaikhoan = new javax.swing.JButton();
        chuyensangdangnhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 153)));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Tên đăng nhập");

        jLabel3.setText("Mật Khẩu");

        jLabel4.setText("Nhập lại mật khẩu");

        Themtaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Themtaikhoan.setText("Thêm");
        Themtaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemtaikhoanActionPerformed(evt);
            }
        });

        chuyensangdangnhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chuyensangdangnhap.setText("Đăng nhập");
        chuyensangdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyensangdangnhapActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Đăng Ký");

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlbh/icon/baseline_person_black_24dp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Themtaikhoan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chuyensangdangnhap))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRetypePasswword, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRetypePasswword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuyensangdangnhap)
                    .addComponent(Themtaikhoan))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int quyen = 0;
    public static String ten = "";
    private void ThemtaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemtaikhoanActionPerformed
        // TODO add your handling code here:
     // Khai báo các biến kết nối CSDL
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    ResultSet rs2 = null;

    try {
        // Lấy kết nối tới CSDL
        conn = new MyDBConnection().getConnection();

        // Lấy thông tin từ các trường nhập liệu trên form
        String MaNhanVien = txtMaNhanVien.getText().trim();
        String TenDangNhap = txtUserName.getText();
        String Password = String.valueOf(txtPassword.getPassword()).trim();
        String NhapLai = String.valueOf(txtRetypePasswword.getPassword());

        // Lấy quyền mặc định từ CSDL
        String Quyen = "";
        String cautruyvan = "SELECT * FROM Quyen WHERE TenQuyen = 'New'";
        pstmt = conn.prepareStatement(cautruyvan);
        rs = pstmt.executeQuery();
        if (rs.next()) {
            Quyen = rs.getString("MaQuyen");
        }

        // Kiểm tra các điều kiện đầu vào
        boolean kt = true;

        if (MaNhanVien.isEmpty() || TenDangNhap.isEmpty() || Password.isEmpty() || NhapLai.isEmpty()) {
            ThongBao("Vui lòng nhập đầy đủ thông tin!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (TenDangNhap.length() < 6 || TenDangNhap.length() > 10) {
            ThongBao("Tên đăng nhập phải từ 6-10 ký tự", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (Password.length() < 6 || Password.length() > 50) {
            ThongBao("Mật khẩu phải nhập nhiều hơn 6 ký tự và ít hơn 50 ký tự", "Lỗi đăng ký", JOptionPane.ERROR_MESSAGE);
        } else if (!KiemTraChuaChuVaSo(Password)) {
            ThongBao("Mật khẩu phải bao gồm chữ IN HOA, chữ thường và số", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!Password.equals(NhapLai)) {
            ThongBao("Nhập lại mật khẩu không khớp", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            // Kiểm tra xem mã nhân viên có tồn tại trong CSDL không
            String cautruyvan2 = "SELECT * FROM NhanVien WHERE MaNhanVien = ?";
            pstmt = conn.prepareStatement(cautruyvan2);
            pstmt.setString(1, MaNhanVien);
            rs2 = pstmt.executeQuery();
            if (!rs2.next()) {
                ThongBao("Mã nhân viên không tồn tại, vui lòng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // Kiểm tra xem tài khoản đã tồn tại trong CSDL chưa
                String cautruyvan3 = "SELECT * FROM Users WHERE MaNhanVien = ?";
                pstmt = conn.prepareStatement(cautruyvan3);
                pstmt.setString(1, MaNhanVien);
                rs2 = pstmt.executeQuery();
                if (rs2.next()) {
                    ThongBao("Tài khoản của nhân viên có mã: " + MaNhanVien + " đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Thêm tài khoản mới vào CSDL
                    String ctv = "INSERT INTO Users VALUES (?, ?, ?, ?, N' ')";
                    pstmt = conn.prepareStatement(ctv);
                    pstmt.setString(1, MaNhanVien);
                    pstmt.setString(2, TenDangNhap);
                    pstmt.setString(3, Password);
                    pstmt.setString(4, Quyen);
                    int rowsAffected = pstmt.executeUpdate();
                    if (rowsAffected > 0) {
                        ThongBao("Đã thêm tài khoản thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        ThongBao("Không thể thêm tài khoản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Đóng tất cả các kết nối và tài nguyên
        try {
            if (rs != null) {
                rs.close();
            }
            if (rs2 != null) {
                rs2.close();
            }
            if (pstmt != null) {
                pstmt.close();
            }
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_ThemtaikhoanActionPerformed

    private void chuyensangdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyensangdangnhapActionPerformed
        // TODO add your handling code here:
         // Đóng form đăng ký
         this.dispose();
        // Tạo một đối tượng DangNhapJDialog
         DangNhapJDialog dangNhapDialog = new DangNhapJDialog((java.awt.Frame) this.getParent(), true);
         // Hiển thị form đăng nhập
         dangNhapDialog.setVisible(true);
    }//GEN-LAST:event_chuyensangdangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangKyJDialog dialog = new DangKyJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Themtaikhoan;
    private javax.swing.JButton chuyensangdangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetypePasswword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
